CREATE TABLE CONTATO
(
    ID SERIAL NOT NULL PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    FAVORITO BOOLEAN,
    FOTO OID,
    CONSTRAINT contato_pkey PRIMARY KEY (id)
)

ALTER TABLE IF EXISTS CONTATO
    OWNER to postgres;